# Generated by Django 6.0 on 2026-01-01 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meta',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='metas/'),
        ),
    ]
