# Generated by Django 6.0 on 2026-01-01 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_alter_meta_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meta',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
