# Generated by Django 6.0 on 2026-01-02 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_alter_meta_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='fecha_gasto',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='fecha_ingreso',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='obligacion',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True),
        ),
    ]
